### PR TITLE
Possible Solutions for Household-Related Issues

### LINKED ISSUE #106: Household Size in Active_List
Right now, we're calculating household size after filtering down to a single row for each client. This means that if they originally had additional household members in that entry with them but those household members have a different entry selected to display on the list, those members will not be counted in their household size. This is causing roughly 120 clients to display a household size smaller than the number of people originally associated with their entry. I think it may make sense to move the household size calculation up into the `co_currently_homeless` pipes at the top.

To view the rows with differing household sizes, run the following code after all but the last two lines of the active_list script:

```
compare_hh_size <- co_currently_homeless %>%
  group_by(HouseholdID) %>%
  mutate(HouseholdSize = n()) %>%
  ungroup() %>%
  inner_join(
    active_list %>%
      select(HouseholdID, HouseholdSize),
    by = "HouseholdID") %>%
  filter(HouseholdSize.x != HouseholdSize.y)
```

### LINKED ISSUE #109: Household Aggregations
I'm looking at the active from the user's perspective, and I have a couple systemic questions about what is intended to be rolled up and what isn't. If we decide to roll up either of these, the sections may also need to be moved up higher in the code, depending on the disposition of Issue #106 

For instance, we have a column that's labelled Income, but it's only looking at the income of the head of household. As a user, I would probably expect that to include whether anyone in the household has income, not just the person shown, but that could be a reflection of the set-up I'm used to?

Another example is score: it's rare, but we have a few instances of someone who is not listed as head of household having a higher score than the head of household. It may make sense to display the highest score in the last year for all household members instead of just the head of household's. To see those households, run the following code after the scores are joined to the `active_list` data frame:
```
active_list_test <- active_list %>%
  group_by(HouseholdID) %>%
  mutate(highest_score = max(Score)) %>%
  ungroup() %>%
  filter(Score != highest_score & hoh == 1)
```

### PR DESCRIPTION
**Pull request by gwenbeebe**
I have two related Issues open about household aggregation and roll-ups, so I'm consolidating the code to address those here. The initial commit just abbreviates the current household size calculation, and will be followed by additional commits with explanatory comments. 

- intent is to fix #106 and fix #109

### CODE REVIEW

**Comment by gwenbeebe** [comment]
This commit moves the household size calculation to the very top of the code to fix the issue of household calculations only including members with a shared selected entry. For additional context, here is the text of the original issue:

> Right now, we're calculating household size after filtering down to a single row for each client. This means that if they originally had additional household members in that entry with them but those household members have a different entry selected to display on the list, those members will not be counted in their household size. This is causing roughly 120 clients to display a household size smaller than the number of people originally associated with their entry. I think it may make sense to move the household size calculation up into the `co_currently_homeless` pipes at the top.

**Comment by gwenbeebe** [comment]
This commit moves the `DisabilityInHH` calculation to the top of the code because this household calculation was only including members with a shared selected entry. Looking at the 10/9 data, there were six households not previously identified as having a member with a disability that are now caught with this change (179935 and 158925 are examples).

**Comment by gwenbeebe** [comment]
I extended this to move chronic determinations up above this filtering too--if you could [take a look](https://github.com/gwenbeebe/COHHIO_HMIS/pull/2) at those modifications and let me know whether you think they should be included in this PR, that would be great!

**Comment by kiadso** [comment]
I reviewed that and I definitely think they should be included here, thank you!

**Comment by gwenbeebe** [comment]
Merged, we're all set on this one!

**Pull request merged**
