### PR TITLE
Efficiency Update for Active_List Deduplication

### PR DESCRIPTION
**Pull request by gwenbeebe**
I updated the active_list handling of multiple entries to do the same thing in fewer lines. I commented out each section of the pipes, so the changes should hopefully be easy to follow. 

One thing I noticed while doing this is that we'll always show the most recent literally homeless entry even if they have been entered in a housing program more recently, so we're labeling clients as in a housing program even though the displayed program information is for a shelter or the unsheltered provider. I recreated that in the update here, but wanted to double check whether that's intentional? Some of our county guessing might be easier if we prioritized pulling in the housing program information over literally homeless information, since by definition they should have more county information.

### CODE REVIEW

**Comment by gwenbeebe** [comment]
One thing to consider as we're talking about which entry should be displayed here--especially if it isn't necessarily showing the most recent entry, it might be worth revisiting the DV join. 

Right now we're displaying the information as of entry into the displayed program enrollment. Maybe we should be looking at the most recently reported DV status for each client, regardless of the program entering it or the information collection stage. DV status can definitely change over the course of system engagement, especially for folks that have been around a while.

**Comment by kiadso** [comment]
It was intentional to show the LH entry because I was thinking this is how people will know where this household is currently. Like geographically where is this household, was my thought. But I see both sides to this and I have had a user ask how they can know which PH project they're in and my only answer was like you'd have to look it up in HMIS. But we could add it to the Current Situation column, just like I've done for Referrals. Like we could make it say "Has Entry into RRH/PSH: [provider name]".
Regarding the DV comment, I agree totally with this assessment and keeping the most recent Data Collection event is a good idea. Thank you so much for making this code more efficient!

**Comment by gwenbeebe** [comment]
I added a section that shows the housing provider in the `Situation` column IF it is not the program already displayed in the `ProjectName` column. I was going back and forth on this, and it would easy to have the `Situation` column always display the provider name if that's what we want, but I decided on this for now in the name of not duplicating information that's already in the row. 

I also updated the DV code to match the discussion above!

**Comment by kiadso** [comment]
I like the decision to only show the PH project if the one listed is different. Also the DV code, showing the most recent here. Thank you for these edits!!!

**Pull request merged**
