### PR TITLE
Adding chronic determination to VBNL

### PR DESCRIPTION
**Pull request by gwenbeebe**
For this, I just used the chronic logic from the active list because we've already gone over it with fine-toothed combs! The primary difference here is that it's based on each individual, with no consideration of the rest of the household, so we can skip ahead to using the SinglyChronic logic as an independent determinant and put the whole status in a single case statement (neat!). I use the most recent entry information for this to keep it consistent with where we're pulling the rest of the person-level information like eligibility and housing track.

I haven't removed your thought process notes about chronicity in the following section because I didn't know if moving the logic in cohorts was still on the table...it feels like it might be less necessary now? But didn't want to make that call, so I left the notes alone. Let me know what you think!

### CODE REVIEW

**Comment by kiadso** [comment]
Yes- thus far, we have considered any hh member where someone in the hh is chronic to be chronic. I split it out in the code just because you have to figure out the who's chronic on their own before you can apply that to the hh members. It's definitely much easier to only consider the individual's chronicity in the code, but going by the definition, I felt it was necessary to be sure it's applied to all hh members. Not sure if this would mean that moving the code to cohorts.R would make the most sense, but either way, I think if we're going to change the method of considering chronicity so that it's individual only, I need to check with EM first. I can do that Tuesday!

**Comment by gwenbeebe** [comment]
Sounds like a plan! I wasn't sure from your commented notes. I think the exact way you're using the list might matter a lot here? Of course the head of household has to be chronic for the household to be considered chronic, which usually doesn't matter because you can just record the chronic person as the head of household! But because we're specifically working with vets here, if we're looking at veteran-specific resources for them will it matter for their veteran program eligibility whether they are actually the head of household or just...in the household? 

Like, if we're trying to fill a program that specifically serves chronic vets, would we want to flag a household for that if one adult is a veteran and the other adult is chronic? I'm not sure. Maybe if we do use households, we could have an extra category that's like "Chronic By Association" or something.

**Comment by kiadso** [comment]
Omg, I don't think I even realized it had to be the hoh all this time!! Just sitting with that for a second here. It definitely does say that in the decision tree thing, like very clearly! I think in my head I glossed over it because assigning the hoh is really immaterial, inconsistent, important and unimportant all at the same time! So I was just ignoring it I guess?

I looked it up in the USICH Criteria and Benchmarks documentation to see how it says to handle what you're getting at, like when the veteran is in a hh with a chronic person and here's what it says!

> A family with an adult head of household (or if there is no adult in the family, a minor head of household) who meets all of the criteria in paragraphs (1) or (2) of this definition, including a family whose composition has fluctuated while the head of household has been homeless.

So it does make it seem like we should at the very least check hhs where there's a veteran who's not the hoh to see if the hoh is chronic for the purposes of the report calculations. It seems like the benchmarks doc wants us to count that veteran as chronic if that's the case. (Whereas I was counting them as chronic even if a non-hoh was chronic. I can tell you EM will prefer this to the way I had it, lol. :)

Thanks so much for bringing this up- I appreciate it!

**Comment by gwenbeebe** [comment]
Okay, I'm pretty excited about this! What I ended up doing was taking all the chronic logic and throwing it in a function you can apply to a dataframe in pipes to add the client's chronic status. This is neat because it recreates the logic I was using to determine each vet's chronicity before, but it ALSO makes it really easy to grab the chronic status for each relevant HoH, which can then be rolled up to the household level and joined back to the veteran we're interested in. 

And because it just lives in `functions`, we can apply it other places too if we want (`active_list`, maybe? or even higher?) and use whatever household roll-up logic makes sense in those locations.

When we're displaying this in RMinor_elevated, how do you want that to look? We could over-write their existing status if the HoH's is higher than theirs, use shading or an icon to indicate when the HoH is chronic and the vet isn't, or add a line below the existing Chronic Status text with the additional information. For what it's worth, the data I'm using right now only has one non-chronic vet in it that's getting flagged as having a chronic HoH, so it's pretty rare that this will have an impact!

**Comment by kiadso** [comment]
I don't know how important it would be to the users of the report why the Vet is being counted as Chronic, so I'm not sure we need to indicate it at all.

This makes me think more about how I have "Aged In" as a type of chronicity. Like, same thought as above, a user of the report shouldn't care about that except maybe to realize they haven't acted fast enough to get them out of wherever they are and it caused a veteran to start being counted as Chronic that wasn't at Entry. But are they really getting that message and is it actionable? The "Nearly" Chronic designation is actionable and useful, but I'm rethinking "Aged In".

I think it's good to be able to break these out (with the function) but for these purposes, do we need the users to know which nuance caused the calculation? I'm curious what you think about it!

**Comment by kiadso** [comment]
Also I'm super excited about that functionnn!

**Comment by gwenbeebe** [comment]
Hm...I would keep it in my system, but only because I think it would usually be a data quality issue in mine (we have some pretty messy exit data still, yay imports). If you're confident that people are in the shelters that HMIS says they're in, I'm now leaning towards combining it with the standard Chronic level. 

We could also have that as a setting in the function, like it defaults to `aged_in = FALSE` but if you set it to `aged_in = TRUE` you can still call it with that intermediate level, in case it's sometimes more appropriate? Thinking out loud here a little.

**Comment by kiadso** [comment]
Yea, I think especially our veterans are kept pretty clear of missing Exits, in large part due to the Active List and all the meetings. And YES I like the adding an "aged_in" argument. omg this is the best

**Comment by gwenbeebe** [comment]
Okay, I added the optional argument to the function (left it null when called on the vets, so no `Aged In` there anymore) and also updated the function to create an ordered factor instead of a regular one. Unordered was sorting fine in the app, but when I tried comparing veterans' chronicities to their HoHs' chronicities I realized they couldn't be compared like ordinals without making that update!

Veterans with HoHs who have a higher-priority chronic status will now see that HoH's status reflected in RMinor.

**Pull request merged**
