### PR TITLE
Supporting functions: profile_script, and demos for server.R

### PR DESCRIPTION
**Pull request by yogat3ch**
Individual commits will have further details

### CODE REVIEW

**Comment by kiadso** [comment]
Hi, I don't want to combine all the HMIS functions like served_between(), etc. because I feel it's more readable and meaningful to keep them separate.

**Comment by yogat3ch** [comment]
Hi @kiadso, (tagging since I dont know that the notification will come through otherwise)

> Hi, I don't want to combine all the HMIS functions like served_between(), etc. because I feel it's more readable and meaningful to keep them separate.

I can definitely understand the need to maintain readability when the `between` functions appear in the script. 
The reason for combining them was for:
1. efficiency (prompted by the results of the profiling)
2. they rely on nearly identical sub-processes (checking of class and coercion of start/end arguments)
3. their outcomes are filtered `data.frame`s
4. They take identical arguments (a `start` and `end`) so the syntax is very similar. 

With the rework, they would be called as follows:
`served_between(., ReportStart, ReportEnd)` would be `between_(served)`
and so forth
`between_(stayed)`
`between_(exited)`
`between_(entered)`

Do you feel like this compromises the legibility too much?

Since the `operating` and `beds_available` actually return a mutated logical column (a different output), I can see how these could be separated, and I think that might be a good idea... I added them in because they also fit all the criteria mentioned above, though their output is different. 

The syntax would be nearly identical to above with these two as well:

`between_(operating)` / `operating_between`

I'm curious to hear your thoughts with the additional info

**Comment by kiadso** [comment]
I do think served_between() is easier to understand for HMIS folks than between_(served). I think there's value in rewriting them to handle the dates better, in terms of the profiler results, etc. I like the last code chunk a lot: qpr_leavers %>% served_between().

**Comment by yogat3ch** [comment]
> I do think served_between() is easier to understand for HMIS folks than between_(served). I think there's value in rewriting them to handle the dates better, in terms of the profiler results, etc. I like the last code chunk a lot: qpr_leavers %>% served_between().

Ok, i've created a new branch & PR (#93 ) to continue the discussion related directly to the handling of these functions. I've posed a question there related to what you would like the output of the functions to be. In your comments in *00_functions.R*, it seems like you would have preferred to use the functions in a pipe (and thus output a `data.frame`) to pass along to the next function in the pipe. However, the functions are currently used nested within `filter` calls - necessitating a modification of the existing code to adopt the behavior. The question is posed on the new branch PR, so feel free to answer over there.

**Comment by kiadso** [comment]
Hi, is this PR is now irrelevant since we created the HMIS package, closing, but let me know if there's something here we needed! Also thank you!

**Pull request closed without merging**
